# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FRIDAYUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(0, 0, 1368, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.Gif_1.sizePolicy().hasHeightForWidth())
        self.Gif_1.setSizePolicy(sizePolicy)
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("GUIfiles/aibackgroundpicolo.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1220, 570, 121, 41))
        self.pushButton_start.setStyleSheet("background-color:Transparent;")
        self.pushButton_start.setText("")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(1220, 630, 121, 41))
        self.pushButton_close.setStyleSheet("background-color:Transparent;")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(1220, 570, 121, 45))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("GUIfiles/Start.png"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(1220, 630, 121, 41))
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("GUIfiles/Quit.png"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(1230, 480, 101, 81))
        self.Gif_2.setStyleSheet("background-color:Transparent;")
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("GUIfiles/Earth_Template.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, -50, 350, 141))
        self.pushButton.setStyleSheet("background-color:Transparent;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, -40, 391, 231))
        self.pushButton_2.setStyleSheet("background-color:Transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 600, 191, 101))
        self.pushButton_3.setStyleSheet("background-color:Transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 630, 161, 81))
        self.pushButton_4.setStyleSheet("background-color:Transparent;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(620, 660, 141, 61))
        self.pushButton_5.setStyleSheet("background-color:Transparent;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(605, 650, 171, 111))
        self.pushButton_6.setStyleSheet("background-color:Transparent;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(-30, -20, 181, 151))
        self.Gif_3.setStyleSheet("background-color:Transparent;\n"
"")
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("GUIfiles/mic.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(0, 0, 1368, 1000))
        self.bg_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_3.setText("")
        self.bg_3.setPixmap(QtGui.QPixmap("GUIfiles/aibackgroundpicolo.gif"))
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 0, 450, 101))
        self.pushButton_7.setStyleSheet("background-color:Transparent;\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.bg_3.raise_()
        self.Gif_1.raise_()
        self.bg_1.raise_()
        self.pushButton_start.raise_()
        self.bg_2.raise_()
        self.pushButton_close.raise_()
        self.Gif_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.Gif_3.raise_()
        self.pushButton_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "DY PATIL UNIVERSITY"))
        self.pushButton_2.setText(_translate("MainWindow", "Title : Friday The Age Of AI"))
        self.pushButton_3.setText(_translate("MainWindow", "Group Members"))
        self.pushButton_4.setText(_translate("MainWindow", "Jayesh Nanekar"))
        self.pushButton_5.setText(_translate("MainWindow", "Krishna Kulthe"))
        self.pushButton_6.setText(_translate("MainWindow", "Sagar Sutarpanchal"))
        self.pushButton_7.setText(_translate("MainWindow", "School Of Engineering And Technology"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
